Made further improvements of the output messages
This was required for a more user-friendly approach

diff --git a/functions_clipboard b/functions_clipboard
--- a/functions_clipboard
+++ b/functions_clipboard
@@ -13,9 +13,10 @@ function clipboard {
     #
     # second argument can only have value -o (override files automatically when pasting) or no value
     if [[ ! -z $2 ]] && [[ '-o' != $2 ]]; then
-	echo "Invalid second argument $2";
-	echo 'Please enter -o or no value';
 	> "$commandFile";
+	echo "Invalid second argument: $2";
+	echo 'Clipboard erased';
+	echo 'Please enter -o or no value';
 	return 1;
     fi
     # first argument specifies the operation type (move/copy), no other value allowed
@@ -44,8 +45,9 @@ function clipboard {
     echo 'Enter keyword: ';
     read keyword;
     if [[ -z $keyword ]]; then
-	echo 'No input. Please try again';
 	> "$commandFile";
+	echo 'No input. Clipboard erased';
+	echo 'Please try again';
 	return 1;
     fi
     #
@@ -53,6 +55,8 @@ function clipboard {
     echo $operation > "$commandFile";
     echo `pwd` >> "$commandFile";
     echo "$keyword" >> "$commandFile";
+    echo 'The command has been successfully built';
+    echo 'Please choose the destination directory and run the paste function to execute it';
     return 0; 
 }
 # This function emulates a 'PASTE' operation
@@ -60,7 +64,7 @@ function psit {
     # check that the file that contains the components of the paste command exists
     if [[ ! -f "$commandFile" ]]; then
 	echo "Parameters file $commandFile does not exist";
-	echo 'Please run the clipboard command with one of the allowed arguments';
+	echo 'Please run the clipboard function with one of the allowed arguments';
 	return 1;
     fi 
     # read the command components and build the paste command
@@ -71,30 +75,31 @@ function psit {
     # decide on the type of "paste" operation (move/copy)
     if [[ -z $operation ]]; then
 	echo 'The clipboard is empty';
-	echo 'Please run the clipboard command with one of the allowed arguments and then try again';
+	echo 'Please run the clipboard function with one of the allowed arguments and then try again';
 	return 1;
     elif [[ $operation == 'mv -i' ]] || [[ $operation == 'mv' ]]; then
 	action='move';
     elif [[ $operation == 'cp -ir' ]] || [[ $operation == 'cp -r' ]]; then
 	action='copy';
     else
-	echo "Incorrect entry in the command file. Erasing file content";
-	echo 'Please run the clipboard command with one of the allowed arguments and the try again';
 	> "$commandFile";
+	echo "Incorrect entry in the command file. Clipboard erased";
+	echo 'Please run the clipboard function with one of the allowed arguments and the try again';
 	return 1;
     fi
     # check that the source directory is valid
     if [[ ! -d "$sourceDir" ]]; then
+	> "$commandFile";
 	echo "Invalid source directory $sourceDir";
 	echo 'It might have been deleted, renamed or moved';
-	> "$commandFile";
+	echo 'Clipboard erased';
 	return 1;
     fi
     # check that the keyword used for determining the files to be moved/copied exists
     if [[ -z $keyword ]]; then
-	echo 'No keyword found';
-	echo 'Please run the clipboard command with one of the allowed arguments and then try again';
 	> "$commandFile";
+	echo 'No keyword found. Clipboard erased';
+	echo 'Please run the clipboard function with one of the allowed arguments and then try again';
 	return 1;
     fi
     # ensure the source and destination directory are NOT the same
@@ -106,9 +111,21 @@ function psit {
     command="$operation $keyword \"$destDir\"";
     cd "$sourceDir";
     eval "$command";
-    # flush the command file if the paste operation was a move operation or the paste operation was not successful
-    if [[ $? != 0 ]] || [[ $action == 'move' ]]; then
+    status=$?;
+    # provide status of command execution and erase the content of the command file if required
+    if [[ 0 == $status ]]; then
+	echo "Finished the $action operation";
+    else
+	echo "The $action operation finished with errors or user chose to override only part of the content";
+	echo 'Please check the source and destination directories';
+    fi
+    if [[ $action == 'move' ]]; then
 	> "$commandFile";
+	echo 'Clipboard erased';
+	echo 'For a new operation please run the clipboard function with one of the allowed arguments';
+    else
+	echo 'Clipboard NOT erased';
+	echo 'The copy operation can be repeated in the same or in a different directory';
     fi
     # return to destination directory (from which the function was executed)
     cd - > /dev/null;
@@ -117,7 +134,7 @@ function psit {
 # this function empties the clipboard
 function emptyClipboard {
     > "$commandFile";
-    echo 'Clipboard erased!';
+    echo 'Clipboard erased';
     return 0;
 }
 # this function displays the clipboard
